### ISSUE TITLE
Empty DataFrame

### ISSUE THREAD

**Issue by jseward311** [dhimmel/hackjohn#2]
Any reason I would be getting this message? 

```
Empty DataFrame
Columns: [Date, Trailhead, Spaces]
Index: []
```

**Comment by dhimmel** [comment]
Hey @jseward311, as of code version 3d634c2746e86b46bea4fbbcf3bda89571298ff8, that output indicates that no vacancies were found. The DataFrame refers to the table that contains one row for each permit opportunity matching your parameters. Since it has no rows, what you show above is printed rather than the actual table.

For reference, here is the full output when no spaces are found:

```
Spaces available as of 2019-05-10

Empty DataFrame
Columns: [Date, Trailhead, Spaces]
Index: []

According to https://www.nps.gov/yose/planyourvisit/fulltrailheads.htm
Yosemite Reservations: 209-372-0740 (Monday–Friday 9:00am–4:30pm)
```

I see how this is not the most informative message. However, note that you shouldn't get a telegram notification when no spaces are found, but yes the empty dataframe is printed.

**Comment by dhimmel** [comment]
In https://github.com/dhimmel/hackjohn/commit/4bd1961f9a2e449f5f7df4bb3c92d7b914167ecb, I change it so when there is no vacancy the output will be like:

```
Spaces available as of 2019-05-10:

NO VACANCY

According to https://www.nps.gov/yose/planyourvisit/fulltrailheads.htm
Yosemite Reservations: 209-372-0740 (Monday–Friday 9:00am–4:30pm)

output has changed: True
```
